name       : kpimtextedit
version    : 18.04.3
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kpimtextedit-18.04.3.tar.xz : 81e4ec27e7fb8b3b5a014160c706183d497c5ee688dcfbb36dcbc7022871143b
license    : LGPL-2.1
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
