name       : kpimtextedit
version    : 20.12.2
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kpimtextedit-20.12.2.tar.xz : 7e9833d9210be7f5d4261d81f5a55f6111b21d186e4b07cb226be9d517ff9bb1
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - grantlee-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
