name       : kpimtextedit
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kpimtextedit-17.08.3.tar.xz : 4bfb84508ea32e2d05a7f0985f871307bb0ddbe4a9f3076d177d46a7ebfecef7
license    : LGPL-2.1
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
