name       : kpimtextedit
version    : 20.08.1
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kpimtextedit-20.08.1.tar.xz : 2664e6cbe520fa345e18db071dd5b8a5b4cf9b0fc7317eb04849005228666189
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5TextToSpeech)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
