name       : kpimtextedit
version    : 19.08.2
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kpimtextedit-19.08.2.tar.xz : e565774d77f310165fc44c8b109ef835aae82a2f763d89d1ffb6e5b820cd850d
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5TextToSpeech)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
