name       : kpimtextedit
version    : 19.04.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kpimtextedit-19.04.1.tar.xz : 2fb2dc59a016dd70424c0fbad45ca1d750c2578f539e79d89bcace85bafd24d1
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5TextToSpeech)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
