name       : kpimtextedit
version    : 18.12.2
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kpimtextedit-18.12.2.tar.xz : 7419b4bb0323ef375159d985f82274b1dcc9bb6d0c997ec79c79449952a07daf
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5TextToSpeech)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
