name       : kpimtextedit
version    : 21.04.1
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kpimtextedit-21.04.1.tar.xz : 231cb4d59475dcd681513eb9976808c70bcad461fd8521478fe4f89a73d386b8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - grantlee-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
