name       : kpimtextedit
version    : 20.08.3
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kpimtextedit-20.08.3.tar.xz : a298386e53e78a09da2f3916ab5ebaf538bf621bd77574d41f72cb05d72f99d4
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5TextToSpeech)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
