name       : kpimtextedit
version    : 18.04.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kpimtextedit-18.04.0.tar.xz : c8680d9ccc619ae5d8d588cb69f980745c570e38035df6bb17e592450a913280
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel : ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
