name       : kpimtextedit
version    : 20.12.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kpimtextedit-20.12.3.tar.xz : 3377669943dfe8990d011a2ceb9d01759518f5097732424afa723ffd7e61931e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - grantlee-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
