name       : kpimtextedit
version    : 21.12.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kpimtextedit-21.12.0.tar.xz : 4157a163a9ecb339baecc19176f03f0478371b1b635187adef4d5ec98681d09f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit
description: |
    KPIMTextedit is a library that provides an enchanced text edit class, see TextEdit.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - grantlee-devel
    - kdesignerplugin-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
